#!/bin/bash 

echo "======== YunoHost Installation ========"
echo "======== Check dependences ========"
DOMAIN=$(hostname -d)
dpkg -l | grep -q lsb-release
if [ $? = 1 ];
then
	apt-get update -qq
	apt-get install lsb-release -y 
fi

echo "======== Check domain ========"
whiptail --title "Yunohost Domain" --yesno "Your domain is $DOMAIN\nDo you want to change this?" 8 78
if [ $? = 0 ];
then
	DOMAIN=$(whiptail --inputbox "Enter your new domain please" 8 78 --title "Yunohost Domain" 3>&1 1>&2 2>&3)
fi

whiptail --title "Yunohost Installation" --yesno "Do you want install Yunhost?" 8 78
if [ $? = 0 ];
then 
	echo "======== Update hostname ========"	
	# Update hostname
	echo "yunohost" > /etc/hostname
	grep -q "yunohost.$DOMAIN" /etc/hosts
	if [ $? = 1 ];
        then
		echo -e "127.0.0.1\tyunohost.$DOMAIN\tyunohost" > /etc/hosts	
		/etc/init.d/hostname.sh start
	fi

	echo "======== Add repository ========"
	#Get gpg key
	wget -O- http://lemonldap-ng.org/_media/rpm-gpg-key-ow2 -q | apt-key add - -qq
	wget -O- http://repo.yunohost.org/yunohost.asc -q | apt-key add - -qq
	grep -q "lemonldap-ng.org" /etc/apt/sources.list
	if [ $? = 1 ];
	then
		echo "deb http://lemonldap-ng.org/deb squeeze main" >> /etc/apt/sources.list
	fi
	grep "yunohost" /etc/apt/sources.list
	if [ $? = 1 ];
        then
		if [ $(lsb_release -is) = "Debian" ];
		then
			echo "deb http://repo.yunohost.org/ squeeze main" >> /etc/apt/sources.list
		elif [ $(lsb_release -is) = "Ubuntu" ];
		then
			echo "deb http://repo.yunohost.org/ precise main" >> /etc/apt/sources.list
		fi
	fi
	
	#Update repo	
	apt-get update -qq
	if [ $? != 0 ] ; 
	then
        	echo "Update Repo Failure"
        	exit 1
	fi
	
	echo "======== Install ========"
	#add answer in debconf db
	debconf-set-selections debconf
 
	#Install yunohost packages
	debconf-apt-progress -- apt-get -y install yunohost yunohost-config yunohost-config-postfix postfix postfix-ldap postfix-policyd-spf-perl -y
	if [ $? != 0 ] ; 
	then
        	echo "Install yunohost Failure"
        	exit 1
	else
		mysqladmin -u root -pyunohost password ''
		service slapd restart 
		service apache2 restart
		service dovecot restart
		service postfix restart
		service ejabberd restart
		service iptables start
		service nscd restart
		service nslcd restart
		echo "======== Installation succes ========"
		  
	fi
	
else 
	echo "======== Installation cancel ========"
	exit 1
fi
