#!/usr/bin/env bash

cat << EOF
----
Patching sources.list to enable unstable repository...
----
EOF

readarray -d '' apt_files < <(find /etc/apt/sources.list /etc/apt/sources.list.d -type f -print0)
for FILE in "${apt_files[@]}"; do
    # (Append 'testing' at the end of lines starting with the yunohost repo..)
    sed -i 's@^deb http://forge.yunohost.org.*@& testing unstable@' "$FILE"
done

cat << EOF
----
Running 'apt-get update'
----
EOF
apt-get update

cat << EOF
----
Running 'apt-get dist-upgrade'
----
EOF
apt-get dist-upgrade -y
